export const LocaleKey = Object.freeze({
    BRAND_GUESSER: 'brand_guesser',
    BRAND_EVERYONE: 'brand_everyone',
    SCORE: 'score_label',
    TRIES: 'score_tries',
    TAP_VINYL: 'hint_tap_vinyl',
    WHOS_SINGING: 'picker_whos_singing',
    ORIGINAL_SONGS: 'catalog_original',
    COVERS: 'catalog_covers',
    EASY: 'difficulty_easy',
    MEDIUM: 'difficulty_medium',
    HARD: 'difficulty_hard',
    IMAGE: 'media_image',
    VIDEO: 'media_video',
    GUESS: 'action_guess',
    LISTEN: 'action_listen',
    NEXT_TRACK: 'action_next_track',
    CORRECT: 'result_correct',
    OUT_OF_TRIES: 'result_out_of_tries',
    SONG_POINTS: 'result_song_points',
    VOCALOID_POINTS: 'result_vocaloid_points',
    TOTAL_POINTS: 'result_total_points',
    GUESS_PLACEHOLDER: 'guess_placeholder',
    FOCUS_CHANGE: 'focus_change',
    FOCUS_RANDOM_POOL: 'focus_random_pool',
    LANGUAGE: 'language_label'
})
